--ICD9, AGE, SAPSI, SURVIVE/DIE FLAG
select id.SUBJECT_ID, id.SAPSI_FIRST, id.ICUSTAY_EXPIRE_FLG, id.ICUSTAY_ADMIT_AGE as AGE, ic.CODE, ic.DESCRIPTION
from MIMIC2V26.ICUSTAY_DETAIL id, MIMIC2V26.ICD9 ic
where id.SUBJECT_ID = ic.SUBJECT_ID 
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20;

--HCO3 first value
select distinct id.SUBJECT_ID, first_value(ce.VALUE1NUM) over (partition by id.SUBJECT_ID order by ce.CHARTTIME asc) as HCO3, ci.LABEL
from MIMIC2V26.ICUSTAY_DETAIL id, MIMIC2V26.ICD9 ic, MIMIC2V26.CHARTEVENTS ce, MIMIC2V26.D_CHARTITEMS ci
where id.SUBJECT_ID = ic.SUBJECT_ID 
and ce.ITEMID = ci.ITEMID
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20
and ce.ITEMID = '3810'; --this is the correct HCO3

--Elixhauser scores
select id.SUBJECT_ID, cs.CONGESTIVE_HEART_FAILURE, cs.CARDIAC_ARRHYTHMIAS, cs.VALVULAR_DISEASE, cs.PULMONARY_CIRCULATION, cs.PERIPHERAL_VASCULAR, cs.HYPERTENSION, cs.PARALYSIS, cs.OTHER_NEUROLOGICAL, cs.DIABETES_COMPLICATED, cs.DIABETES_UNCOMPLICATED, cs.HYPOTHYROIDISM, cs.RENAL_FAILURE, cs.LIVER_DISEASE, cs.PEPTIC_ULCER, cs.AIDS, cs.LYMPHOMA, cs.METASTATIC_CANCER, cs.SOLID_TUMOR, cs.RHEUMATOID_ARTHRITIS, cs.COAGULOPATHY, cs.OBESITY, cs.WEIGHT_LOSS, cs.FLUID_ELECTROLYTE, cs.BLOOD_LOSS_ANEMIA, cs.DEFICIENCY_ANEMIAS, cs.ALCOHOL_ABUSE, cs.DRUG_ABUSE, cs.PSYCHOSES, cs.DEPRESSION
from MIMIC2V26.COMORBIDITY_SCORES cs, MIMIC2V26.ICUSTAY_DETAIL id
where id.SUBJECT_ID = cs.SUBJECT_ID 
and id.HADM_ID = cs.HADM_ID
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20;

--Total urine output for entire ICU stay
select distinct id.SUBJECT_ID, sum(io.VOLUME) over (partition by id.SUBJECT_ID) as TOTAL_URINE
from MIMIC2V26.ICUSTAY_DETAIL id, MIMIC2V26.IOEVENTS io
where id.ICUSTAY_ID = io.ICUSTAY_ID
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20
and io.itemid in (55, 56, 57, 61, 65, 69, 85, 94, 96, 288, 405,
428, 473, 651, 715, 1922, 2042, 2068, 2111, 2119, 2130, 2366, 2463,
2507, 2510, 2592, 2676, 2810, 2859, 3053, 3175, 3462, 3519, 3966, 3987,
4132, 4253, 5927);

--WBC first value
select distinct id.SUBJECT_ID, first_value(le.VALUENUM) over (partition by id.SUBJECT_ID order by le.CHARTTIME asc) as WBC
from MIMIC2V26.ICUSTAY_DETAIL id, MIMIC2V26.LABEVENTS le
where id.ICUSTAY_ID = le.ICUSTAY_ID
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20
and le.ITEMID in (50316, 50468);

--Celsius temperature first value
select distinct id.SUBJECT_ID, first_value(ce.VALUE1NUM) over (partition by id.SUBJECT_ID order by ce.CHARTTIME asc) as TEMPERATURE
from MIMIC2V26.ICUSTAY_DETAIL id, MIMIC2V26.CHARTEVENTS ce
where id.ICUSTAY_ID = ce.ICUSTAY_ID
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20
and ce.ITEMID in (676, 677);

--Fahrenheit temperature first value
select distinct id.SUBJECT_ID, (first_value(ce.VALUE1NUM) over (partition by id.SUBJECT_ID order by ce.CHARTTIME asc) - 32) * 5/9 as TEMPERATURE
from MIMIC2V26.ICUSTAY_DETAIL id, MIMIC2V26.CHARTEVENTS ce
where id.ICUSTAY_ID = ce.ICUSTAY_ID
and id.HOSPITAL_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_FLG = 'Y'
and id.ICUSTAY_FIRST_CAREUNIT = 'MICU' 
and id.SAPSI_FIRST > 20
and ce.ITEMID in (678, 679);